kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{include "geo-addressing-spark-nfs-storage-class.name" .}}
  labels:
    {{- include "geo-addressing-spark-eks.labels" . | nindent 4 }}
provisioner: efs.csi.aws.com

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{include "geo-addressing-spark-nfs-pv.name" .}}
  finalizers: [ ]
  labels:
    {{- include "geo-addressing-spark-eks.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.global.nfs.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{include "geo-addressing-spark-nfs-storage-class.name" .}}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.global.nfs.fileSystemId }}
    volumeAttributes:
      path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{include "geo-addressing-spark-nfs-pvc.name" .}}
  labels:
    {{- include "geo-addressing-spark-eks.labels" . | nindent 4 }}
spec:
  storageClassName: {{include "geo-addressing-spark-nfs-storage-class.name" .}}
  volumeName: {{include "geo-addressing-spark-nfs-pv.name" .}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.nfs.storage }}
